import 'package:dishes/api.dart';
import 'package:flutter/material.dart';
import 'model.dart';
import 'package:flutter/material.dart';

import 'navdrawer.dart';

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  Autogenerated? data;
  @override
  void initState() {
    Api().getData().then((value) => data = value);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    if(data !=null)
    print(data!.branchName);
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          backgroundColor: Colors.white,
          drawer: NavDrawer(),
          appBar: AppBar(
            bottom: const TabBar(
              tabs: [
                Tab(text: "Salads and Soup"),
                Tab(text: "From the Barnyard"),
                Tab(text: "From the Barnyard")
              ],
            ),
          ),
          body:  TabBarView(
            children: [
FutureBuilder(),
              dishesWidget(),
              Icon(
                Icons.crop_square_sharp,
                color: Colors.green,
                size: 36,
              ),
              Icon(
                Icons.crop_square_sharp,
                color: Colors.green,
                size: 36,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class dishesWidget extends StatelessWidget {
  const dishesWidget({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
        margin: EdgeInsets.all(20),
        child: Column(
          children: [
            Row(
              children: [
                Stack(
                  alignment: Alignment.center,
                  children: const [
                    Icon(
                      Icons.crop_square_sharp,
                      color: Colors.green,
                      size: 36,
                    ),
                    Icon(Icons.circle, color: Colors.green, size: 14),
                  ],
                ),
                Text("Spinach")
              ],
            ),
            Row(
              children: [
                Text("data"),
                Spacer(),
                Text("data"),
              ],
            ),
            Text("deatis ldkfklsfsklfs"),
            Container(
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(18),
                color: Colors.green,
              ),
              width: 120,
              child: Row(
                children: [
                  const Icon(
                    Icons.remove,
                    color: Colors.white,
                  ),
                  TextButton(
                      onPressed: () {},
                      child: const Text(
                        "0",
                        style: TextStyle(color: Colors.white),
                      )),
                  const Icon(
                    Icons.add,
                    color: Colors.white,
                  ),
                ],
              ),
            ),
            Spacer(),
          ],
        ));
  }
}
